experiment:
  dataset: movielens_exp
  data_config:
      strategy: fixed
#      train_path: ../data/ventrella_experiment/train2id_dbbook.csv
#      test_path: ../data/ventrella_experiment/test2id_dbbook.csv
      train_path: ../data/ventrella_experiment/train2id_movielens.csv
      test_path: ../data/ventrella_experiment/test2id_movielens.csv
      dataloader: DataSetLoader

  top_k: 5  # takes an int representing the list length
  evaluation:
    #cutoffs: [5, 10]  # maximum length of the recommendation list we want to consider when computing the metric
    simple_metrics: [Precision,Recall,MavF1,nDcg,MRR]
    relevance_threshold: 1  # minimum value of the rating to consider a test transaction relevant for the evaluation process
    paired_ttest: True
    wilcoxon_test: True
  #print_results_as_triplets: True  # generate the evaluation tables with the format: [method,metric,value]
  #gpu: -1  # enable GPU acceleration with Tensorflow
  #config_test: True  # tests our configuration file before the actual run of the experiment
  external_models_path: ../external/models/__init__.py
  models:
#    external.TransE_GUSE:
#      meta:
#        save_recs: False
#    external.TransH_GUSE:
#      meta:
#        save_recs: False
    external.basic_transE:
      meta:
        save_recs: False
    external.basic_transH:
      meta:
        save_recs: False
    external.basic_BERT:
      meta:
        save_recs: False
    external.basic_USE:
      meta:
        save_recs: False
    external.TransE_USE_h1:
      meta:
        save_recs: False
    external.TransH_USE_h1:
      meta:
        save_recs: False
    external.TransE_BERT_h1:
      meta:
        save_recs: False
    external.TransH_BERT_h1:
      meta:
        save_recs: False
    external.TransE_USE_h2:
      meta:
        save_recs: False
    external.TransH_USE_h2:
      meta:
        save_recs: False
    external.TransE_BERT_h2:
      meta:
        save_recs: False
    external.TransH_BERT_h2:
      meta:
        save_recs: False
    external.CFGAN:
      meta:
        save_recs: False
    external.DeepICF:
      meta:
        save_recs: False
    external.MLP:
      meta:
        save_recs: False
    external.WRMF:
      meta:
        save_recs: False
    external.FISM:
      meta:
        save_recs: False
    external.NAIS:
      meta:
        save_recs: False
    external.DAE:
      meta:
        save_recs: False
    external.NeuMF:
      meta:
        save_recs: False
